cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'



urlpatterns = [
    path('' , views.cart_detail , name='cart_detail'),
    path('add/<int:product_id>/' , views.cart_add ,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from account.views import MyLoginView
from account.views import Register ,activate



urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('shop.urls')),
    path('login/', MyLoginView.as_view(), name='login'),
    path('zarinpal/', include('zarinpal.urls')),
    path('account/', include('account.urls')),
    path('cart/' , include('cart.urls')),
    path('orders/' , include('orders.urls')),
    path('coupons/' , include('coupons.urls')),
    path('register/', Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    
    
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupons/urls.py
from django.urls import path

from . import views

app_name = "coupons"






urlpatterns = [
    path('apply/>' ,views.coupon_apply ,name="apply" )
]

orders/urls.py
from django.urls import path
from . import views



app_name = 'orders'






urlpatterns = [
    path('create/' , views.order_create , name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'








urlpatterns = [
    path('' , views.ProductList.as_view() , name='product_list'),
    path('page/<int:page>/' , views.ProductList.as_view() , name='product_list'),
    path('detail/<slug:slug>/' , views.product_detail , name='product_detail'),
    path('category/<slug:slug>/' , views.CategoryList.as_view() , name='category_list'),
    path('offer/' , views.OfferList.as_view() , name='offer_list'),
    path('privacy-policy/',views.privacy_policy,name="privacy-policy"),
    path ('search/' , views.SearchList.as_view() , name='search'),
]

cart/forms.py
from django import forms



PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]



class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    override = forms.BooleanField(required=False , initial=False , widget=forms.HiddenInput )

   

cart/views.py
from django.shortcuts import redirect, render ,get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from shop.models import Product
from coupons.forms import CouponApplyForm
from django.conf import settings


@require_POST
def cart_add(request, product_id ):
    """
    Add a product to the cart or update its quantity
    """
    cart = Cart(request)
    product = get_object_or_404(Product , id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product , quantity=cd['quantity'] , override_quantity=cd['override'])
        request.session['coupon_id'] = None
        return redirect('cart:cart_detail')


@require_POST
def cart_remove(request , product_id):
    cart = Cart(request)
    product = get_object_or_404(Product , id=product_id)
    cart.remove(product)
    request.session['coupon_id'] = None
    return redirect('cart:cart_detail')
        

def cart_detail(request):
    cart = Cart(request)
    form_apply_code = CouponApplyForm()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity':item['quantity'],
            'override':True
        })
    context = {
        'cart':cart,
        'form':form_apply_code,
    }
    return render(request , 'cart/cart_detail.html' , context)

templates/cart/cart_detail.html
{% extends 'product/base.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}



{% block title %}
 سبد خرید

{% endblock %}







{% block content %}
<!-- Start All Title Box -->
<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>سبد خرید</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">فروشگاه</a></li>
                    <li class="breadcrumb-item active">سبد خرید</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End All Title Box -->

<!-- Start Cart  -->
{% if cart %}
<div class="cart-box-main" dir="rtl">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="table-main table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>تصویر</th>
                                <th>نام کالا</th>
                                <th>قیمت واحد</th>
                                <th class="text-center">تعداد</th>
                                <th>جمع</th>
                                <th>حذف کالا</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart %}
                            {% with product=item.product %}
                            
                            <tr>
                                <td class="thumbnail-img">
                                    <a href="#">
                                <img class="img-fluid" src="{{product.image.url}}" alt="" />
                            </a>
                                </td>
                                <td class="name-pr">
                                    <a href="#">
                                {{product.name}}
                            </a>
                                </td>
                                <td class="price-pr">
                                    <p>{{product.price|intcomma }}</p>
                                </td>
                                <td class="quantity-box">
                                    <form action="{% url 'cart:cart_add' product.id %}" method="POST">{% csrf_token %}
                                    <!-- {{item.update_quantity_form.quantity|add_class:"class_quantity_1"}} -->
                                    <input type="number" id="quantity" name="quantity" min="1" max="{{product.Inventory}}" class="class_quantity_1" value="{{item.quantity}}">
                                    {{item.update_quantity_form.override}}
                                    <button class="btn btn-primary" type="submit" > <i class="fa fa-refresh" aria-hidden="true"></i></button>
                                    </form>
                                </td>
                                <td class="total-pr">
                                    <p>{{item.total_price|intcomma}}</p>
                                </td>
                                <td class="remove-pr">
                                    <form action="{% url 'cart:cart_remove' product.id %}" method="POST">{% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash-o"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            {% endwith %}
                           {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="row my-5">
            <div class="col-lg-6 col-sm-6">
                <div class="coupon-box">
                    <div class="input-group input-group-sm">
                        <form action="{% url 'coupons:apply' %}" method="POST">{% csrf_token %}
                            <div class="col-md-6 mb-3">
                                <label for="code" style="float: right;">استفاده از کوپن تخفیف</label>
                                {{form.code}}
                                <!-- <input type="text" class="form-control" id="lastName" placeholder="" value="" required> -->
                                <button class="btn btn-primary mt-2" style="float: right;" type="submit">اعمال کد تخفیف</button>
                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-sm-6 mt-5">
                <div class="update-box">
                    <a href="{% url 'shop:product_list' %}">
                    <input value="ادامه خرید" type="submit">
                    </a>
                   
                </div>
            </div>
        </div>
        {% if cart.coupon %}
        <div class="row my-5">
            <div class="col-lg-8 col-sm-12"></div>
            <div class="col-lg-4 col-sm-12">
                <div class="order-box">
                    <hr>
                    <div class="d-flex gr-total">
                        <h5 class="text-danger">قیمت اصلی : </h5>
                        <div class="ml-auto h5 text-danger"> {{cart.get_total_price|intcomma}} </div>
                    </div>
                    <hr>
                    <div class="d-flex gr-total">
                        <h5>مقدار تخیف :</h5>
                        <div class="ml-auto h5"> {{cart.get_discount|intcomma}} </div>
                    </div>
                    <hr>
                    <div class="d-flex gr-total">
                        <h5 class="text-success">جمع کل سفارش: </h5>
                        <div class="ml-auto h5 text-success"> {{cart.get_total_price_after_discount|intcomma}} </div>
                    </div>
                    <hr> </div>
            </div>
            {% if user.is_authenticated %}
            <div class="col-12 d-flex shopping-box"><a href="{% url 'orders:order_create' %}" class="ml-auto btn hvr-hover">تسویه حساب</a> </div>
            {% else %}
            <div class="col-12 d-flex shopping-box"><a href="{% url 'orders:order_create' %}" class="ml-auto btn hvr-hover">برای تسویه ثبت نام کنید</a> </div>
            {% endif %}
        </div>
        {% else %}
        <div class="row my-5">
            <div class="col-lg-8 col-sm-12"></div>
            <div class="col-lg-4 col-sm-12">
                <div class="order-box">
                    <hr>
                    <div class="d-flex gr-total">
                        <h5>جمع کل سفارش: </h5>
                        <div class="ml-auto h5"> {{cart.get_total_price|intcomma}} </div>
                    </div>
                    <hr> </div>
            </div>
            {% if user.is_authenticated %}
            <div class="col-12 d-flex shopping-box"><a href="{% url 'orders:order_create' %}" class="ml-auto btn hvr-hover">تسویه حساب</a> </div>
            {% else %}
            <div class="col-12 d-flex shopping-box"><a href="{% url 'register' %}" class="ml-auto btn hvr-hover">برای تسویه ثبت نام کنید</a> </div>
            {% endif %}
        </div>
        {% endif %}
        
        

    </div>
</div>
<!-- End Cart -->
{% else %}
<div class="row" dir="rtl" style="height: 400px;width: 90%; margin: auto;">
    <div class="col-md-12 text-center">
        <div>
            <img src="{% static 'product/images/empty-cart.svg' %}" alt="سبد خرید خالی">
        </div>
        <p style="font-size:30px;color: black;">سبد خرید شما خالی است !</p>
        <p>می توانید برای مشاهده محصولات به صفحه زیر بروید :</p>
        <a href="{% url 'shop:product_list' %}">
        <button class="btn btn-primary mt-4">محصولات ما</button>
        </a>
    </div>
</div>
{% endif %}

{% endblock %}