account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.urls import reverse_lazy




app_name = 'account'

urlpatterns = [
    #--------------------------AUTH--------------------------------
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.MyPasswordChangeView.as_view(template_name='registration/password/password_change_form.html',success_url=reverse_lazy('account:password_change_done')), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password/password_change_done.html'), name='password_change_done'),
    path('password_reset/', views.password_reset_request , name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password/password_reset_confirm.html",success_url=reverse_lazy('account:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password/password_reset_complete.html'), name='password_reset_complete'),  
]


urlpatterns += [
    path ('' ,views.Home.as_view() , name = 'home'),
    #----------------------PRODUCTS----------------------
    path ('product/list' ,views.ProductListAdmin.as_view() , name = 'product-list'),
    path ('product/create/' ,views.ProductCreate.as_view() , name = 'product-create'),
    path ('product/update/<int:pk>' ,views.ProductUpdate.as_view() , name = 'product-update'),
    path ('product/delete/<int:pk>' ,views.ProductDelete.as_view() , name = 'product-delete'),

    #----------------------CATEGORIES----------------------
    path ('category/list/' ,views.CategoryListAdmin.as_view() , name = 'category-list'),
    path ('category/create/' ,views.CategoryCreate.as_view() , name = 'category-create'),
    path ('category/update/<int:pk>' ,views.CategoryUpdate.as_view() , name = 'category-update'),
    path ('category/delete/<int:pk>' ,views.CategoryDelete.as_view() , name = 'category-delete'),


    path ('coupon/list/' ,views.CouponListAdmin.as_view() , name = 'coupon-list'),
    path ('coupon/create/' ,views.CouponCreate.as_view() , name = 'coupon-create'),
    #-----------------------ORDERS---------------------------
    path ('order/list/' ,views.OrderList.as_view() , name = 'order-list'),
    path ('order/history/' ,views.order_history_user , name = 'order-history-user'),

    path ('profile/' ,views.Profile.as_view() , name = 'profile'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'



urlpatterns = [
    path('' , views.cart_detail , name='cart_detail'),
    path('add/<int:product_id>/' , views.cart_add ,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from account.views import MyLoginView
from account.views import Register ,activate



urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('shop.urls')),
    path('login/', MyLoginView.as_view(), name='login'),
    path('zarinpal/', include('zarinpal.urls')),
    path('account/', include('account.urls')),
    path('cart/' , include('cart.urls')),
    path('orders/' , include('orders.urls')),
    path('coupons/' , include('coupons.urls')),
    path('register/', Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    
    
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'








urlpatterns = [
    path('' , views.ProductList.as_view() , name='product_list'),
    path('page/<int:page>/' , views.ProductList.as_view() , name='product_list'),
    path('detail/<slug:slug>/' , views.product_detail , name='product_detail'),
    path('category/<slug:slug>/' , views.CategoryList.as_view() , name='category_list'),
    path('offer/' , views.OfferList.as_view() , name='offer_list'),
    path('privacy-policy/',views.privacy_policy,name="privacy-policy"),
    path ('search/' , views.SearchList.as_view() , name='search'),
]

templates/product/category_list.html
{% extends 'product/base.html' %}
<!-- Extend base -->
{% load static %}
<!-- Load Static -->
{% load widget_tweaks %}
{% load humanize %}






{% block content %}
<nav aria-label="breadcrumb " dir="rtl" >
    <ol class="breadcrumb justify-content-center" style="background-color: white;">
      <li class="breadcrumb-item"><a href="{% url 'shop:product_list' %}"><i class="fa fa-home" aria-hidden="true" style="font-size: 18px;"></i></a></li>
      {% for product in object_list %}
      {% if forloop.first %}
      <li class="breadcrumb-item active" aria-current="page">{{product.category.name}}</li>
      {% endif %}
      {% endfor %}
    </ol>
  </nav>
<div class="categories-shop">
    <div class="container">
        <div class="row" dir="rtl">
            {% for product in object_list %}
            <div class="col-lg-4 col-md-4 col-sm-6 mt-2 ">
                <section class="neumorphism" style="background-color: white;">


                    <div class="card" style="border-radius: 15px;">
                        <div class="bg-image hover-overlay ripple ripple-surface ripple-surface-light" data-mdb-ripple-color="light" style="width: 100%; height: 170px;">
                            <img src="{{product.image.url}}" style="border-top-left-radius: 15px; border-top-right-radius: 15px;height:150px; width:100%" class="img-fluid" alt="{{product.name}}" />
                            <a href="#!">
                                <div class="mask"></div>
                            </a>
                        </div>
                        <div class="card-body pb-0">
                            <div class="d-flex justify-content-between">
                                <div>
                                    <p><a href="#!" class="text-dark">{{product.name}}</a></p>
                                    <p class="small text-muted">{{product.category}}</p>
                                </div>
                                <div>
                                    <div class="d-flex flex-row justify-content-end mt-1 mb-4 text-danger">
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                    </div>
                                    <p class="small text-muted">Rated 4.0/5</p>
                                </div>
                            </div>
                        </div>
                        <hr class="my-0" />
                        <div class="card-body pb-0">
                            <div class="d-flex justify-content-between">
                                <p><a href="#!" class="text-dark">{{product.price|intcomma}} تومان</a></p>
                                <p class="text-dark">#### 8787</p>
                            </div>
                            {% if product.status == 'a' %}
                            <p class="badge bg-success text-light" style="font-size: 16px;">موجود</p>
                            {% elif product.status == 'u' %}
                            <p class="badge bg-danger text-light" style="font-size: 16px;">ناموجود</p>
                            {% else %}
                            <p class="badge bg-warning text-light" style="font-size: 16px;">قابل سفارش</p>
                            {% endif %}
                        </div>

                        <hr class="my-0" />
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center pb-2 mb-1">
                                <a href="{% url 'shop:product_detail' product.slug %}">
                                <button type="button" class="btn btn-dark mb-3">مشاهده</button>
                                </a>
                                <form action="{% url 'cart:cart_add' product.id %}" method="POST">{% csrf_token %}
                                    <div class="form-group quantity-box">
                                        <!-- <label class="control-label">تعداد</label> -->
                                        {{form.quantity|attr:"value:1"|add_class:"class_quantity_1"}}
                                        <button type="submit" class="btn btn-success">افزودن به سبد خرید</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-evenly">
        <a href="http://localhost:8000/category/mouse">
        <div class="col-lg-5 col-md-8 card-box-rounded mt-3" style="background-color: #E0B0FF;">
            <div class="col-6 mt-2" style="float: right;">
                <img src="{% static 'product/images/box-1.png' %}" style="height: 150px;width: 100%; margin-top: 5px;" alt="mouse">
            </div>
            
            <div class="col-6 text-center box-card-ghab" style="background-color: #E0B0FF;">
                <div style="font-size: 24px;">انواع موس</div>
            </div>
        </a>
        </div>
        <a href="http://localhost:8000/category/keyboard">
        
        <div class="col-lg-5 col-md-8 card-box-rounded mt-3" style="background-color: #B3FFB0;margin-left: auto;">
            <div class="col-6 mt-2" style="float: right;">
                <img src="{% static 'product/images/box-2.png' %}" style="height: 150px;width: 100%; margin-top: 5px;" alt="keyboard">
            </div>
            <div class="col-6 text-center box-card-ghab" style="background-color:#B3FFB0;">
                <div style="font-size: 24px;">انواع کیبورد</div>
            </div>
        </a>
        </div>
        <a href="http://localhost:8000/category/mrofon">
        <div class="col-lg-5 col-md-8 card-box-rounded mt-3 " style="background-color: #7AC8FF;">
            <div class="col-6 mt-2" style="float: right;">
                <img src="{% static 'product/images/box-3.png' %}" style="height: 150px;width: 100%; margin-top: 5px;" alt="microphone">
            </div>
            <div class="col-6 text-center box-card-ghab" style="background-color: #7AC8FF;">
                <div style="font-size: 24px;">انواع میکروفون </div>
            </div>
        </a>
        </div>
        <a href="http://localhost:8000/category/sandali">
        <div class="col-lg-5 col-md-8 card-box-rounded mt-3 " style="background-color: #DC785A;margin-left: auto;">
            <div class="col-6 mt-2" style="float: right;">
                <img src="{% static 'product/images/box-4.png' %}" style="height: 150px;width: 100%; margin-top: 5px;" alt="chair">
            </div>
            <div class="col-6 text-center box-card-ghab" style="background-color: #DC785A;">
                <div style="font-size: 24px;">انواع صندلی </div>
            </div>
        </a>
        </div>
        

    </div>
</div>
<!-- End Categories -->

<div class="main-top mt-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="text-light text-center">
                    ارسال ایمن به سراسر کشور <i class="fas fa-truck" style="color: #ef394e;"></i>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="main-top mt-3">
    <div class="container-fluid">
        <div class="row ">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                <div class="text-light text-center ">
                    پیشنهادات شگفت انگیز <i class="fas fa-fire" style="color: #ef394e;"></i>
                </div>
            </div>

        </div>
    </div>
</div>

<!-- Start Blog  -->
<div class="latest-blog">
    <div class="container">

        <div class="row">
            {% for pish in offers %}

            <div class="col-md-12 col-lg-3 col-xl-3  mt-3 mr-2">
                <div class="card " style="width: 18rem;">
                    <img src="{{pish.image.url}}" class="card-img-top" alt="{{pish.name}}" style="height: 150px;" >
                    <div class="card-body">
                        <h5 class="card-title">{{pish.name}}</h5>
                        <p class="card-text">{{pish.description|safe|truncatewords:10}}</p>
                        <div class="d-flex justify-content-between align-items-center pb-2 mb-1">

                            <a href="{% url 'shop:product_detail' pish.slug %}">
                                <button type="button" class="btn btn-dark rounded-circle"><i class="fas fa-eye fs-5"></i></button>
                                </a>
                            

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="col-lg-2 col-md-12 mt-3">
                <img src="{% static 'product/images/pishnahad.png' %}" style="height: 330px" alt="offer">
                <div class="text-center">
                    <a href="{% url 'shop:offer_list' %}">
                    <button type="button" class="btn btn-dark mt-2" style="background-color: rgba(51,51,51,1);"><i class="fas fa-chevron-left"></i> مشاهده همه</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>



{% endblock %}

templates/product/home.html
{% extends 'product/base.html' %}
<!-- Extend base -->
{% load static %}
<!-- Load Static -->
{% load humanize %}
{% load widget_tweaks %}


{% block title %}
 لذت گیم با مگاگیم

{% endblock %}


{% block content %}
<!-- Start Slider -->
<div id="slides-shop" class="cover-slides slide-size">
    <ul class="slides-container">
        <li class="text-center">
            <img src="{% static 'product/images/card-1.webp' %}" alt="مگاگیم">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="m-b-20"><strong>لذت گیم با <br> مگاگیم</strong></h1>
                        <p class="m-b-40">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است </p>
                        
                    </div>
                </div>
            </div>
        </li>
        <li class="text-center">
            <img src="{% static 'product/images/card-2.webp' %}" alt="مگاگیم">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="m-b-20"><strong>لذت گیم با <br> مگاگیم</strong></h1>
                        <p class="m-b-40">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است </p>
                        
                    </div>
                </div>
            </div>
        </li>
        <li class="text-center">
            <img src="{% static 'product/images/card-3.webp' %}" alt="مگاگیم">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="m-b-20"><strong>لذت گیم با <br> مگاگیم</strong></h1>
                        <p class="m-b-40">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است </p>
                    </div>
                </div>
            </div>
        </li>
    </ul>
    <!-- <div class="slides-navigation">
        <a href="#" class="next"><i class="fas fa-angle-right" ></i></a>
        <a href="#" class="prev"><i class="fas fa-angle-left" ></i></a>
    </div> -->
</div>
<!-- End Slider -->
<div class="categories-shop">
    <div class="container">
        <div class="row " dir="rtl">
            {% for product in object_list %}
            <div class="col-lg-4 col-md-4 col-sm-6 mt-2 ">
                <section class="neumorphism" style="background-color: white;">


                    <div class="card" style="border-radius: 15px;">
                        <div class="bg-image hover-overlay ripple ripple-surface ripple-surface-light" data-mdb-ripple-color="light" style="width: 100%; height: 170px;">
                            <img src="{{product.image.url}}" style="border-top-left-radius: 15px; border-top-right-radius: 15px;height:150px; width:100%" class="img-fluid" alt="{{product.name}}" />
                            <a href="#!">
                                <div class="mask"></div>
                            </a>
                        </div>
                        <div class="card-body pb-0">
                            <div class="d-flex justify-content-between">
                                <div>
                                    <p><a href="#!" class="text-dark">{{product.name}}</a></p>
                                    <p class="small text-muted">{{product.category}}</p>
                                </div>
                                <div>
                                    <div class="d-flex flex-row justify-content-end mt-1 mb-4 text-danger">
                                        
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        <hr class="my-0" />
                        <div class="card-body pb-0">
                            <div class="d-flex justify-content-between">
                                <p><a  class="text-dark">{{product.price|intcomma}} تومان</a></p>
                                
                            </div>
                            <div>
                            {% if product.Inventory == 1 %}
                            <p class="badge bg-warning text-light">تنها 1 عدد در انبار موجود است</p>
                            {% elif product.Inventory > 1 %}
                            <p class="badge bg-success text-light">{{product.Inventory}} عدد در انبار موجود است</p>
                            {% else %}
                            <p class="badge bg-danger text-light">در انبار موجود نمیباشد</p>
                            {% endif %}
                            </div>
                            {% if product.status == 'a' and product.Inventory > 0 %}

                                    <p class="badge bg-success text-light" style="font-size: 16px;">موجود</p>
                            {% elif product.status == 'c' and product.Inventory > 0 %}
                            <p class="badge bg-warning text-light" style="font-size: 16px;">قابل سفارش</p>
                            {% else %}
                            <p class="badge bg-danger text-light" style="font-size: 16px;">ناموجود</p>
                            {% endif %}
                        </div>

                        <hr class="my-0" />
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center pb-2 mb-1">
                                <a href="{% url 'shop:product_detail' product.slug %}">
                                <button type="button" class="btn btn-dark mb-3">مشاهده</button>
                                </a>
                                {% if product.Inventory > 0 and product.status == 'a' or product.Inventory > 0 and product.status == 'c'%}
                                
                                <form action="{% url 'cart:cart_add' product.id %}" method="POST">{% csrf_token %}
                                    <div class="form-group quantity-box">
                                        <!-- <label class="control-label" for="tentacles">تعداد</label> -->
                                        <input type="number" id="quantity" name="quantity" min="1" max="{{product.Inventory}}" class="class_quantity_1" value="1">
                                        <!-- {{form.quantity|attr:"value:1"|add_class:"class_quantity_1"}} -->
                                        <button type="submit" class="btn btn-success">افزودن به سبد خرید</button>
                                    </div>
                                </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            {% if page_obj.has_previous %}
            <a class="page-link" href="{% url 'shop:product_list' page_obj.previous_page_number %}" ><i class="fa fa-angle-left" aria-hidden="true"></i> صفحه قبلی</a> {% endif %}
        </li>
        <li class="page-item">
            {% if page_obj.has_next %}
            <a class="page-link" href="{% url 'shop:product_list' page_obj.next_page_number %}">صفحه بعدی <i class="fa fa-angle-right" aria-hidden="true"></i></a> {% endif %}
        </li>
    </ul>
</nav>


<div class="container">
    <div class="row justify-content-evenly">
        <a href="http://localhost:8000/category/mouse">
        <div class="col-lg-5 col-md-8 card-box-rounded mt-3" style="background-color: #E0B0FF;">
            <div class="col-6 mt-2" style="float: right;">
                <img src="{% static 'product/images/box-1.png' %}" style="height: 150px;width: 100%; margin-top: 5px;">
            </div>
            
            <div class="col-6 text-center box-card-ghab" style="background-color: #E0B0FF;">
                <div style="font-size: 24px;">انواع موس</div>
            </div>
        </a>
        </div>
        <a href="http://localhost:8000/category/keyboard">
        
        <div class="col-lg-5 col-md-8 card-box-rounded mt-3" style="background-color: #B3FFB0;margin-left: auto;">
            <div class="col-6 mt-2" style="float: right;">
                <img src="{% static 'product/images/box-2.png' %}" style="height: 150px;width: 100%; margin-top: 5px;">
            </div>
            <div class="col-6 text-center box-card-ghab" style="background-color:#B3FFB0;">
                <div style="font-size: 24px;">انواع کیبورد</div>
            </div>
        </a>
        </div>
        <a href="http://localhost:8000/category/mrofon">
        <div class="col-lg-5 col-md-8 card-box-rounded mt-3 " style="background-color: #7AC8FF;">
            <div class="col-6 mt-2" style="float: right;">
                <img src="{% static 'product/images/box-3.png' %}" style="height: 150px;width: 100%; margin-top: 5px;">
            </div>
            <div class="col-6 text-center box-card-ghab" style="background-color: #7AC8FF;">
                <div style="font-size: 24px;">انواع میکروفون </div>
            </div>
        </a>
        </div>
        <a href="http://localhost:8000/category/sandali">
        <div class="col-lg-5 col-md-8 card-box-rounded mt-3 " style="background-color: #DC785A;margin-left: auto;">
            <div class="col-6 mt-2" style="float: right;">
                <img src="{% static 'product/images/box-4.png' %}" style="height: 150px;width: 100%; margin-top: 5px;">
            </div>
            <div class="col-6 text-center box-card-ghab" style="background-color: #DC785A;">
                <div style="font-size: 24px;">انواع صندلی </div>
            </div>
        </a>
        </div>
        

    </div>
</div>
<!-- End Categories -->

<div class="main-top mt-3">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="text-light text-center">
                    ارسال ایمن به سراسر کشور <i class="fas fa-truck" style="color: #ef394e;"></i>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="main-top mt-3">
    <div class="container-fluid">
        <div class="row ">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
                <div class="text-light text-center ">
                    پیشنهادات شگفت انگیز <i class="fas fa-fire" style="color: #ef394e;"></i>
                </div>
            </div>

        </div>
    </div>
</div>

<!-- Start Blog  -->
<div class="latest-blog">
    <div class="container">

        <div class="row">
            {% for pish in offers %}

            <div class="col-md-12 col-lg-3 col-xl-3  mt-3 mr-2">
                <div class="card " style="width: 18rem;">
                    <img src="{{pish.image.url}}" class="card-img-top" alt="{{pish.name}}" style="height: 150px;">
                    <div class="card-body">
                        <h5 class="card-title">{{pish.name}}</h5>
                        <p class="card-text">{{pish.description|safe|truncatewords:10}}</p>
                        <div class="d-flex justify-content-between align-items-center pb-2 mb-1">

                            <a href="{% url 'shop:product_detail' pish.slug %}"><button type="button" class="btn btn-dark rounded-circle"><i class="fas fa-eye fs-5"></i></button></a>
                            <!-- <button type="button" class="btn btn-success rounded-circle"><i class="fas fa-shopping-cart fs-5"></i></button> -->

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="col-lg-2 col-md-12 mt-3">
                <img src="{% static 'product/images/pishnahad.png' %}" style="height: 330px">
                <div class="text-center">
                    <a href="{% url 'shop:offer_list' %}">
                    <button type="button" class="btn btn-dark mt-2" style="background-color: rgba(51,51,51,1);"><i class="fas fa-chevron-left"></i> مشاهده همه</button>
                </a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>



{% endblock %}

templates/product/search_list.html
{% extends 'product/base.html' %}
{% load humanize %}
{% load widget_tweaks %}





{% block content %}


<div class="categories-shop">
    <div class="container">
        <div class="row justify-content-center">
        <div class="alert alert-info col-8 text-center " role="alert" >
           <h3> :عبارت جستجو شده</h3><span>{{search}}</span>
        </div>
        </div>
        <div class="row mt-3" dir="rtl">
            {% for product in object_list %}
            <div class="col-lg-4 col-md-4 col-sm-6 mt-2 ">
                <section class="neumorphism" style="background-color: white;">


                    <div class="card" style="border-radius: 15px;">
                        <div class="bg-image hover-overlay ripple ripple-surface ripple-surface-light" data-mdb-ripple-color="light" style="width: 100%; height: 170px;">
                            <img src="{{product.image.url}}" style="border-top-left-radius: 15px; border-top-right-radius: 15px;height:150px; width:100%" class="img-fluid" alt="{{product.name}}" />
                            <a href="#!">
                                <div class="mask"></div>
                            </a>
                        </div>
                        <div class="card-body pb-0">
                            <div class="d-flex justify-content-between">
                                <div>
                                    <p class="text-dark">{{product.name}}</p>
                                    <p class="small text-muted">{{product.category}}</p>
                                </div>
                                <!-- <div>
                                    <div class="d-flex flex-row justify-content-end mt-1 mb-4 text-danger">
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                    </div>
                                    <p class="small text-muted">Rated 4.0/5</p>
                                </div> -->
                            </div>
                        </div>
                        <hr class="my-0" />
                        <div class="card-body pb-0">
                            <div class="d-flex justify-content-between">
                                <p class="text-dark">{{product.price|intcomma}} تومان</p>
                                <p class="text-dark">#### 8787</p>
                            </div>
                            {% if product.status == 'a' %}
                            <p class="badge bg-success text-light" style="font-size: 16px;">موجود</p>
                            {% elif product.status == 'u' %}
                            <p class="badge bg-danger text-light" style="font-size: 16px;">ناموجود</p>
                            {% else %}
                            <p class="badge bg-warning text-light" style="font-size: 16px;">قابل سفارش</p>
                            {% endif %}
                        </div>

                        <hr class="my-0" />
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center pb-2 mb-1">
                                <a href="{% url 'shop:product_detail' product.slug %}">
                                <button type="button" class="btn btn-dark mb-3">مشاهده</button>
                                </a>
                                <form action="{% url 'cart:cart_add' product.id %}" method="POST">{% csrf_token %}
                                    <div class="form-group quantity-box">
                                        <!-- <label class="control-label">تعداد</label> -->
                                        {{form.quantity|attr:"value:1"|add_class:"class_quantity_1"}}
                                        <button type="submit" class="btn btn-success">افزودن به سبد خرید</button>
                                    </div>
                                </form>
                                
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            
        
                
            
            {% endfor %}
        </div>
    </div>
</div>
{% if not object_list %}
<div class="container">
<div class="row justify-content-center">
    <div class="col-8">
        <h2 class="text-center">متاسفانه عبارت شما یافت نشد</h2>
        
        <a href="{% url 'shop:product_list' %}"><button class="btn btn-info ml-4 mb-5" >بازگشت به صفحه اصلی</button></a>
        
    </div>
</div>
</div>
{% endif %}



{% endblock %}