cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'



urlpatterns = [
    path('' , views.cart_detail , name='cart_detail'),
    path('add/<int:product_id>/' , views.cart_add ,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from account.views import MyLoginView
from account.views import Register ,activate



urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('shop.urls')),
    path('login/', MyLoginView.as_view(), name='login'),
    path('zarinpal/', include('zarinpal.urls')),
    path('account/', include('account.urls')),
    path('cart/' , include('cart.urls')),
    path('orders/' , include('orders.urls')),
    path('coupons/' , include('coupons.urls')),
    path('register/', Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    
    
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'








urlpatterns = [
    path('' , views.ProductList.as_view() , name='product_list'),
    path('page/<int:page>/' , views.ProductList.as_view() , name='product_list'),
    path('detail/<slug:slug>/' , views.product_detail , name='product_detail'),
    path('category/<slug:slug>/' , views.CategoryList.as_view() , name='category_list'),
    path('offer/' , views.OfferList.as_view() , name='offer_list'),
    path('privacy-policy/',views.privacy_policy,name="privacy-policy"),
    path ('search/' , views.SearchList.as_view() , name='search'),
]

templates/product/partials/category_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-default bootsnav">
    <div class="container">
        <!-- Start Header Navigation -->
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
        </button>
            <a class="navbar-brand" href="{% url 'shop:product_list' %}"><img src="{% static 'product/images/mega.png' %}" class="logo" alt="mega game" style="margin-left: 30px;margin-bottom: -50px;" width="300px" height="180px"></a>
        </div>
        <!-- End Header Navigation -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-menu">
            <ul dir="rtl" style="margin-right: auto;" class="nav navbar-nav ml-auto" data-in="fadeInDown" data-out="fadeOutUp">
                <li class="nav-item active"><a class="nav-link" href="{% url 'shop:product_list' %}">خانه</a></li>
                <li class="dropdown">
                    <a href="#" class="nav-link dropdown-toggle " data-toggle="dropdown">محصولات </a>
                    <ul class="dropdown-menu">
                        {% for cat in category %}
                        <li><a href="{% url 'shop:category_list' cat.slug %}">{{cat.name}}</a></li>
                        
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item active"><a class="nav-link" href="#">درباره ما</a></li>
                <li class="nav-item active"><a class="nav-link" href="#">ارتباط با ما</a></li>
            </ul>
        </div>
        <form class="form-inline justify-content-center "  action="{% url 'shop:search' %}" method="get" style="margin: auto;">
            <input type="search" id="formsearch" class="form-control text-right" placeholder="...جست و جو" name="q" />
            
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-search"></i>
              </button>
        </form>
        <!-- /.navbar-collapse -->

        <!-- Start Atribute Navigation -->
        <div class="attr-nav">
            <ul>
                
                <li class="nav-item">
                    <a href="{% url 'cart:cart_detail' %}" >
                        <i class="fa fa-shopping-cart" ></i>
                        
                        {% if request.session.cart %}
                        <span class="badge bg-info text-light">{{cart|length}}</span>
                        {% endif %}
                    </a>
                </li>
            </ul>
        </div>
        <!-- End Atribute Navigation -->
    </div>
    <!-- Start Side Menu -->
    <!-- <div class="side">
        <a href="#" class="close-side"><i class="fa fa-times"></i></a>
        <li class="cart-box">
            <ul class="cart-list">
                <li>
                    <a href="#" class="photo"><img src="images/img-pro-01.jpg" class="cart-thumb" alt="" /></a>
                    <h6><a href="#">Delica omtantur </a></h6>
                    <p>1x - <span class="price">$80.00</span></p>
                </li>
                <li>
                    <a href="#" class="photo"><img src="images/img-pro-02.jpg" class="cart-thumb" alt="" /></a>
                    <h6><a href="#">Omnes ocurreret</a></h6>
                    <p>1x - <span class="price">$60.00</span></p>
                </li>
                <li>
                    <a href="#" class="photo"><img src="images/img-pro-03.jpg" class="cart-thumb" alt="" /></a>
                    <h6><a href="#">Agam facilisis</a></h6>
                    <p>1x - <span class="price">$40.00</span></p>
                </li>
                <li class="total">
                    <a href="#" class="btn btn-default hvr-hover btn-cart">VIEW CART</a>
                    <span class="float-right"><strong>Total</strong>: $180.00</span>
                </li>
            </ul>
        </li>
    </div> -->
    <!-- End Side Menu -->
</nav>