account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.urls import reverse_lazy




app_name = 'account'

urlpatterns = [
    #--------------------------AUTH--------------------------------
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.MyPasswordChangeView.as_view(template_name='registration/password/password_change_form.html',success_url=reverse_lazy('account:password_change_done')), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password/password_change_done.html'), name='password_change_done'),
    path('password_reset/', views.password_reset_request , name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password/password_reset_confirm.html",success_url=reverse_lazy('account:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password/password_reset_complete.html'), name='password_reset_complete'),  
]


urlpatterns += [
    path ('' ,views.Home.as_view() , name = 'home'),
    #----------------------PRODUCTS----------------------
    path ('product/list' ,views.ProductListAdmin.as_view() , name = 'product-list'),
    path ('product/create/' ,views.ProductCreate.as_view() , name = 'product-create'),
    path ('product/update/<int:pk>' ,views.ProductUpdate.as_view() , name = 'product-update'),
    path ('product/delete/<int:pk>' ,views.ProductDelete.as_view() , name = 'product-delete'),

    #----------------------CATEGORIES----------------------
    path ('category/list/' ,views.CategoryListAdmin.as_view() , name = 'category-list'),
    path ('category/create/' ,views.CategoryCreate.as_view() , name = 'category-create'),
    path ('category/update/<int:pk>' ,views.CategoryUpdate.as_view() , name = 'category-update'),
    path ('category/delete/<int:pk>' ,views.CategoryDelete.as_view() , name = 'category-delete'),


    path ('coupon/list/' ,views.CouponListAdmin.as_view() , name = 'coupon-list'),
    path ('coupon/create/' ,views.CouponCreate.as_view() , name = 'coupon-create'),
    #-----------------------ORDERS---------------------------
    path ('order/list/' ,views.OrderList.as_view() , name = 'order-list'),
    path ('order/history/' ,views.order_history_user , name = 'order-history-user'),

    path ('profile/' ,views.Profile.as_view() , name = 'profile'),
]

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'



urlpatterns = [
    path('' , views.cart_detail , name='cart_detail'),
    path('add/<int:product_id>/' , views.cart_add ,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include 
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from account.views import MyLoginView
from account.views import Register ,activate



urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('shop.urls')),
    path('login/', MyLoginView.as_view(), name='login'),
    path('zarinpal/', include('zarinpal.urls')),
    path('account/', include('account.urls')),
    path('cart/' , include('cart.urls')),
    path('orders/' , include('orders.urls')),
    path('coupons/' , include('coupons.urls')),
    path('register/', Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    
    
]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'








urlpatterns = [
    path('' , views.ProductList.as_view() , name='product_list'),
    path('page/<int:page>/' , views.ProductList.as_view() , name='product_list'),
    path('detail/<slug:slug>/' , views.product_detail , name='product_detail'),
    path('category/<slug:slug>/' , views.CategoryList.as_view() , name='category_list'),
    path('offer/' , views.OfferList.as_view() , name='offer_list'),
    path('privacy-policy/',views.privacy_policy,name="privacy-policy"),
    path ('search/' , views.SearchList.as_view() , name='search'),
]

zarinpal/urls.py
from django.urls import path
from . import views


app_name = 'zarinpal'

urlpatterns = [
    path('request/', views.send_request, name='request'),
    path('verify/', views.verify , name='verify'),
]

zarinpal/models.py
from django.db import models

# Create your models here.

zarinpal/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect ,render
from orders.models import Order, OrderItem
import requests
import json
from django.core.mail import EmailMessage
# from .tasks import payment_completed







MERCHANT = "7QRXP08Y-VA0D-R4T4-AOF3-FXYXRAFGGV5T"
ZP_API_REQUEST = "https://banktest.ir/gateway/zarinpal/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = "https://banktest.ir/gateway/zarinpal/pg/rest/WebGate/PaymentVerification.json"
ZP_API_STARTPAY = "https://banktest.ir/gateway/zarinpal/pg/StartPay/{authority}"
amount = 11000  # Rial / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
email = 'email@example.com'  # Optional
mobile = '09123456789'  # Optional
# Important: need to edit for realy server.
CallbackURL = 'https://mega-game.ir/zarinpal/verify/'


def send_request(request):
	global total_cost
	order_id = request.session.get('order_id')
	order = get_object_or_404(Order,id=order_id)
	total_cost = order.get_total_cost()
	total_cost = total_cost * 10 #Change Rial to Toman
	req_data = {
		"merchant_id": MERCHANT,
		"amount": total_cost,
		"callback_url": CallbackURL,
		"description": description,
		"metadata": {"mobile": mobile, "email": email}
	}
	req_header = {"accept": "application/json",
				  "content-type": "application/json'"}
	req = requests.post(url=ZP_API_REQUEST, data=json.dumps(
		req_data), headers=req_header)
	authority = req.json()['data']['authority']
	if len(req.json()['errors']) == 0:
		return redirect(ZP_API_STARTPAY.format(authority=authority))
	else:
		e_code = req.json()['errors']['code']
		e_message = req.json()['errors']['message']
		return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")


def verify(request):
	order_id = request.session.get('order_id')
	order = get_object_or_404(Order,id=order_id)
	t_status = request.GET.get('Status')
	t_authority = request.GET['Authority']
	if request.GET.get('Status') == 'OK':
		req_header = {"accept": "application/json",
					  "content-type": "application/json'"}
		req_data = {
			"merchant_id": MERCHANT,
			"amount": total_cost,
			"authority": t_authority
		}
		req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
		if len(req.json()['errors']) == 0:
			t_status = req.json()['data']['code']
			if t_status == 100:
				order.paid = True
				order.save()
				if request.user.email:
					mail_subject = "ثبت سفارش "
				message = "مشتری گرامی سفارش شما ثبت شد و پس از بررسی، سفارش برای شما ارسال میشود"
				email = EmailMessage(
							mail_subject,
							message,
							to=[request.user.email]
				)
				email.send()
				return render(request,"zarinpal/success.html",{"id":str(req.json()['data']['ref_id'])})
			elif t_status == 101:
				return render(request,"zarinpal/submited.html",{"status":str(req.json()['data']['message'])})
			else:
				return render(request,"zarinpal/failed.html",{"status":str(req.json()['data']['message'])})
		else:
			return render(request,"zarinpal/error.html")
	else:
		return render(request,"zarinpal/cancel.html")
	   

templates/zarinpal/cancel.html
{% extends 'product/base.html' %}


{% block content %}

<h1 class="text-danger">پرداخت شما انجام نشد</h1>

<p>your status:{{status}}</p>

{% endblock %}

templates/zarinpal/error.html
{% extends 'product/base.html' %}


{% block content %}

<div class="container">
    <div class="row" dir="rtl">
        <div class="col">
            <div class="card">
                <div class="card-header text-center">
                  عدم ثبت سفارش
                </div>
                <div class="card-body">
                  <h3 class="card-title text-center text-danger">{{user.get_full_name}} عزیز پرداخت شما ثبت نشد.</h3>
                  <a href="{% url 'shop:product_list' %}" class="btn btn-primary text-center">بازگشت به صفحه اصلی</a>
                </div>
              </div>
        </div>
    </div>
    </div>


{% endblock %}

templates/zarinpal/failed.html
{% extends 'product/base.html' %}


{% block content %}

<div class="container">
    <div class="row" dir="rtl">
        <div class="col">
            <div class="card">
                <div class="card-header text-center">
                  عدم ثبت سفارش
                </div>
                <div class="card-body">
                  <h3 class="card-title text-center text-warning">{{user.get_full_name}} عزیز پرداخت شما ثبت نشد.</h3>
                  <p class="card-text text-center">اطلاعات: {{status}}</p>
                  <a href="{% url 'shop:product_list' %}" class="btn btn-primary text-center">بازگشت به صفحه اصلی</a>
                </div>
              </div>
        </div>
    </div>
    </div>


{% endblock %}

templates/zarinpal/submited.html
{% extends 'product/base.html' %}


{% block content %}

<div class="container">
    <div class="row" dir="rtl">
        <div class="col">
            <div class="card">
                <div class="card-header text-center">
                  عدم ثبت سفارش
                </div>
                <div class="card-body">
                  <h3 class="card-title text-center text-info">{{user.get_full_name}} عزیز پرداخت شما ثبت نشد.</h3>
                  <p class="card-text text-center">اطلاعات: {{status}}</p>
                  <a href="{% url 'shop:product_list' %}" class="btn btn-primary text-center">بازگشت به صفحه اصلی</a>
                </div>
              </div>
        </div>
    </div>
    </div>


{% endblock %}

templates/zarinpal/success.html
{% extends 'product/base.html' %}


{% block content %}
<div class="container">
<div class="row" dir="rtl">
    <div class="col">
        <div class="card">
            <div class="card-header text-center">
              ثبت سفارش
            </div>
            <div class="card-body">
              <h3 class="card-title text-center text-success">{{user.get_full_name}} عزیز سفارش شما ثبت شد.</h3>
              <p class="card-text text-center">آیدی سفارش شما : {{id}}</p>
              <p class="card-text text-center">شما میتوانید در پنل کاربری لیست سفارشات خود را مشاهده کنید</p>
              <a href="{% url 'account:order-history-user' %}" class="btn btn-primary text-center">لیست سفارشات من</a>
            </div>
          </div>
    </div>
</div>
</div>


{% endblock %}